/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors */

#ifndef _Included_de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
#define _Included_de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: props */
/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    openTheGate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_openTheGate
  (JNIEnv *, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    closeTheGate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_closeTheGate
  (JNIEnv *, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    absElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Matrix;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_absElem__Lde_rwth_1aachen_techinfo_ltilib_Matrix_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    absElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Vector;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_absElem__Lde_rwth_1aachen_techinfo_ltilib_Vector_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    absElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Matrix;Lde/rwth_aachen/techinfo/ltilib/Matrix;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_absElem__Lde_rwth_1aachen_techinfo_ltilib_Matrix_2Lde_rwth_1aachen_techinfo_ltilib_Matrix_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    absElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Vector;Lde/rwth_aachen/techinfo/ltilib/Vector;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_absElem__Lde_rwth_1aachen_techinfo_ltilib_Vector_2Lde_rwth_1aachen_techinfo_ltilib_Vector_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    logElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Matrix;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_logElem__Lde_rwth_1aachen_techinfo_ltilib_Matrix_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    logElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Vector;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_logElem__Lde_rwth_1aachen_techinfo_ltilib_Vector_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    logElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Matrix;Lde/rwth_aachen/techinfo/ltilib/Matrix;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_logElem__Lde_rwth_1aachen_techinfo_ltilib_Matrix_2Lde_rwth_1aachen_techinfo_ltilib_Matrix_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    logElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Vector;Lde/rwth_aachen/techinfo/ltilib/Vector;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_logElem__Lde_rwth_1aachen_techinfo_ltilib_Vector_2Lde_rwth_1aachen_techinfo_ltilib_Vector_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    squareElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Matrix;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_squareElem__Lde_rwth_1aachen_techinfo_ltilib_Matrix_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    squareElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Vector;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_squareElem__Lde_rwth_1aachen_techinfo_ltilib_Vector_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    squareElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Matrix;Lde/rwth_aachen/techinfo/ltilib/Matrix;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_squareElem__Lde_rwth_1aachen_techinfo_ltilib_Matrix_2Lde_rwth_1aachen_techinfo_ltilib_Matrix_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    squareElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Vector;Lde/rwth_aachen/techinfo/ltilib/Vector;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_squareElem__Lde_rwth_1aachen_techinfo_ltilib_Vector_2Lde_rwth_1aachen_techinfo_ltilib_Vector_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    sqrtElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Matrix;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_sqrtElem__Lde_rwth_1aachen_techinfo_ltilib_Matrix_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    sqrtElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Vector;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_sqrtElem__Lde_rwth_1aachen_techinfo_ltilib_Vector_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    sqrtElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Matrix;Lde/rwth_aachen/techinfo/ltilib/Matrix;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_sqrtElem__Lde_rwth_1aachen_techinfo_ltilib_Matrix_2Lde_rwth_1aachen_techinfo_ltilib_Matrix_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_IteratingFunctors
 * Method:    sqrtElem
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/Vector;Lde/rwth_aachen/techinfo/ltilib/Vector;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_IteratingFunctors_sqrtElem__Lde_rwth_1aachen_techinfo_ltilib_Vector_2Lde_rwth_1aachen_techinfo_ltilib_Vector_2
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
