/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rwth_0005faachen_techinfo_ltilib_Matrix */

#ifndef _Included_de_rwth_0005faachen_techinfo_ltilib_Matrix
#define _Included_de_rwth_0005faachen_techinfo_ltilib_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: props */
/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _getRow
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1getRow
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _getColumn
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1getColumn
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _getRows
 * Signature: (J[I)J
 */
JNIEXPORT jlong JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1getRows
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _getColumns
 * Signature: (J[I)J
 */
JNIEXPORT jlong JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1getColumns
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    openTheGate
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix_openTheGate
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    closeTheGate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix_closeTheGate
  (JNIEnv *, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    copyCtoJava
 * Signature: ([[DII)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix_copyCtoJava___3_3DII
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    copyCtoJava
 * Signature: ([[FII)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix_copyCtoJava___3_3FII
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _setData
 * Signature: (J[[D)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1setData__J_3_3D
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _setData
 * Signature: (J[[F)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1setData__J_3_3F
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _rows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1rows
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _columns
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1columns
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _resize
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1resize
  (JNIEnv *, jobject, jlong, jint, jint, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _fill
 * Signature: (JDIIII)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1fill__JDIIII
  (JNIEnv *, jobject, jlong, jdouble, jint, jint, jint, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _fill
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1fill__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _at
 * Signature: (JII)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1at
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _setAt
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1setAt
  (JNIEnv *, jobject, jlong, jint, jint, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _minimum
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1minimum__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _minimum
 * Signature: (J[I)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1minimum__J_3I
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _maximum
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1maximum__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _maximum
 * Signature: (J[I)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1maximum__J_3I
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _trace
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1trace
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _getDiagonal
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1getDiagonal
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _setRow
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1setRow
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _setColumn
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1setColumn
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _copy
 * Signature: (JJIIII)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1copy__JJIIII
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _copy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1copy__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _compare
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1compare
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _emultiply
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1emultiply__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _emultiply
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1emultiply__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _add
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1add__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _add
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1add__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _add
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1add__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _subtract
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1subtract__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _subtract
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1subtract__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _multiply
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1multiply__JD
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _multiply
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1multiply__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _multiply
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1multiply__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _multiplyV
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1multiplyV
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _leftMultiply
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1leftMultiply__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _leftMultiply
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1leftMultiply__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _outerProduct
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1outerProduct
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _transpose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1transpose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1equals
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Matrix
 * Method:    _prettyCloseTo
 * Signature: (JJD)Z
 */
JNIEXPORT jboolean JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Matrix__1prettyCloseTo
  (JNIEnv *, jobject, jlong, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
