/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rwth_0005faachen_techinfo_ltilib_RectLocation */

#ifndef _Included_de_rwth_0005faachen_techinfo_ltilib_RectLocation
#define _Included_de_rwth_0005faachen_techinfo_ltilib_RectLocation
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: props */
/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    setData
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_setData
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    copy
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/RectLocation;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_copy
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    contains
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_contains__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    contains
 * Signature: (FF)Z
 */
JNIEXPORT jboolean JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_contains__FF
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    distance2
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/RectLocation;)F
 */
JNIEXPORT jfloat JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_distance2__Lde_rwth_1aachen_techinfo_ltilib_RectLocation_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    distance2
 * Signature: (Lde/rwth_aachen/techinfo/ltilib/RectLocation;[F[F)F
 */
JNIEXPORT jfloat JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_distance2__Lde_rwth_1aachen_techinfo_ltilib_RectLocation_2_3F_3F
  (JNIEnv *, jobject, jobject, jfloatArray, jfloatArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    getArea
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_getArea
  (JNIEnv *, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    getAngle
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_getAngle
  (JNIEnv *, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    getAxes
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_getAxes
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    getPosition
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_getPosition
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    openTheGate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_openTheGate
  (JNIEnv *, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    closeTheGate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_closeTheGate
  (JNIEnv *, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_RectLocation
 * Method:    copyCtoJava
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_RectLocation_copyCtoJava
  (JNIEnv *, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
