/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rwth_0005faachen_techinfo_ltilib_UnaryFunctors */

#ifndef _Included_de_rwth_0005faachen_techinfo_ltilib_UnaryFunctors
#define _Included_de_rwth_0005faachen_techinfo_ltilib_UnaryFunctors
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: props */
/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_UnaryFunctors
 * Method:    openTheGate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_UnaryFunctors_openTheGate
  (JNIEnv *, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_UnaryFunctors
 * Method:    closeTheGate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_UnaryFunctors_closeTheGate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
