/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rwth_0005faachen_techinfo_ltilib_Vector */

#ifndef _Included_de_rwth_0005faachen_techinfo_ltilib_Vector
#define _Included_de_rwth_0005faachen_techinfo_ltilib_Vector
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: props */
/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    openTheGate
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector_openTheGate
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    closeTheGate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector_closeTheGate
  (JNIEnv *, jobject);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    copyCtoJava
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector_copyCtoJava___3DI
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    copyCtoJava
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector_copyCtoJava___3FI
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    csubvector
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector_csubvector
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _resize
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1resize
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _setData
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1setData__J_3D
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _setData
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1setData__J_3F
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _fill
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1fill__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _fill
 * Signature: (JDII)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1fill__JDII
  (JNIEnv *, jclass, jlong, jdouble, jint, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _at
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1at
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _setAt
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1setAt
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _copy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1copy
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _sortAscending
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1sortAscending
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _sortDescending
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1sortDescending
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _dot
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1dot
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _emultiply
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1emultiply__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _emultiply
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1emultiply__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _edivide
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1edivide__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _edivide
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1edivide__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _sumOfElements
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1sumOfElements
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _productOfElements
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1productOfElements
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _add
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1add__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _addScaled
 * Signature: (JDJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1addScaled
  (JNIEnv *, jclass, jlong, jdouble, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _add
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1add__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _subtract
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1subtract__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _subtract
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1subtract__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _multiply
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1multiply
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _divide
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1divide
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _add
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1add__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _equals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1equals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _prettyCloseTo
 * Signature: (JJD)Z
 */
JNIEXPORT jboolean JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1prettyCloseTo
  (JNIEnv *, jclass, jlong, jlong, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _maximum
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1maximum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _getIndexOfMaximum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1getIndexOfMaximum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _minimum
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1minimum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _getIndexOfMinimum
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1getIndexOfMinimum
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _concat
 * Signature: (J[Lde/rwth_aachen/techinfo/ltilib/Vector;)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1concat
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _normalize
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1normalize__JDD
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _normalize
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1normalize__JD
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     de_rwth_0005faachen_techinfo_ltilib_Vector
 * Method:    _normalizeSum
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_de_rwth_1aachen_techinfo_ltilib_Vector__1normalizeSum
  (JNIEnv *, jclass, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
